[cats-blender-plugin-unofficial]
src.git = "https://git.disroot.org/Neoneko/Cats-Blender-Plugin.git"
src.branch = "Blender-5x"
fetch.git = "https://git.disroot.org/Neoneko/Cats-Blender-Plugin.git"

[disblock-origin]
src.git = "https://git.allpurposem.at/mat/Disblock-Origin.git"
fetch.git = "https://git.allpurposem.at/mat/Disblock-Origin.git"

[osc-goes-brrr]
src.git = "https://github.com/OscToys/OscGoesBrrr.git"
fetch.git = "https://github.com/OscToys/OscGoesBrrr.git"

[winetricks]
src.git = "https://github.com/Winetricks/winetricks.git"
fetch.git = "https://github.com/Winetricks/winetricks.git"
